### ISSUE TITLE
Team The Crux (07/15/2020)

### ISSUE THREAD

**Issue by MuriloRoque** [EricMbouwe/Wotchd#1]
Pros:
- Editing and deleting features are a nice addition;
- Using scopes to calculate the amount and conditionals to separate grouped and ungrouped are magnific;
- The upload photo feature is very nice too;
- The use of Active Storage is neat.

Recommendation:
- Maybe you could add a label to the photo upload on User Signup.

**Comment by EricMbouwe** [comment]
Thanks
